apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  name: component-base-test1-0
  namespace: default
---
apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  name: component-test1-1
  namespace: default
